"""Slack integration for dispatching accepted action items."""

from typing import List, Dict, Any, Optional
import httpx
from app.utils.config import settings
from app.utils.logging import logger


class SlackIntegration:
    """Formats and dispatches meeting action items to Slack channels."""

    def __init__(self, webhook_url: Optional[str] = None):
        self.webhook_url = webhook_url or settings.slack_webhook_url

    def format_block_kit(self, meeting_title: str, action_items: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Format action items into Slack Block Kit message structure."""
        blocks: List[Dict[str, Any]] = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"📋 Meeting Action Items: {meeting_title}",
                    "emoji": True
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Total Confirmed Tasks:* {len(action_items)}\n_Generated by Meeting Intelligence & Social Dynamics Analyzer_"
                }
            },
            {"type": "divider"}
        ]

        for idx, item in enumerate(action_items, 1):
            owner = item.get("owner", "Unassigned")
            due = item.get("due_date", "Unscheduled")
            priority = item.get("priority", "Medium")
            task = item.get("task", "")
            
            blocks.append({
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*{idx}. {task}*\n• *Owner:* `{owner}`  |  *Due:* `{due}`  |  *Priority:* `{priority}`"
                }
            })

        return {"blocks": blocks}

    async def send_action_items(self, meeting_title: str, action_items: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Send formatted action items to Slack. Mocks dispatch in DEMO_MODE."""
        payload = self.format_block_kit(meeting_title, action_items)

        if settings.demo_mode or not self.webhook_url:
            logger.info("DEMO_MODE: Simulating Slack dispatch for %d action items", len(action_items))
            return {
                "status": "success",
                "mode": "demo_simulated",
                "message": f"Successfully simulated Slack notification to {settings.slack_default_channel}",
                "channel": settings.slack_default_channel,
                "items_sent": len(action_items),
                "payload_preview": payload
            }

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                res = await client.post(self.webhook_url, json=payload)
                if res.status_code == 200:
                    return {
                        "status": "success",
                        "mode": "live",
                        "channel": settings.slack_default_channel,
                        "items_sent": len(action_items)
                    }
                else:
                    return {
                        "status": "error",
                        "message": f"Slack API responded with status {res.status_code}: {res.text}"
                    }
        except Exception as e:
            logger.error("Slack integration exception: %s", str(e))
            return {"status": "error", "message": f"Connection error: {str(e)}"}
